---
layout: post
title: ! 'HOWTO : buy a speaker/surround system for your home cinema and music experiences'
---

<P>Choosing a correct speakerset is actually a real quest, and in order to make that choice, I have taken the following points under consideration:</P>
<P>- make sure you are hearing the speakers/reciever without equalizer/optimizations during a demonstration. Sales reps tend to make high sounds sound overnaturally sharp, and low sounds boomy. While this might sound impressive during a short demonstration, it really starts to get annoying listenig to it for a long time.<BR><BR>-&nbsp;If you are listening to a system with satelites and a seperate&nbsp;sub(woofer) : volume &amp; crossover/cutoff frequency&nbsp;make all the difference, together with the settings of your satelites&nbsp;as large or small speakers (no bass tones from sats &lt;-&gt; bass tones from sats).&nbsp;A sub that is correctly configured shouldn't draw your attention. Please note that in most shops the sub is way to loud in it's config ; listening a whole&nbsp;day to such a sub is guarantead to give you a very big headache.<BR><BR>- Please make sure the bass does stay tight, and does not start 'booming' at higher volume levels.<BR><BR>- Bring your own CD's, and listen to different kinds of music. IMHO accoustic,&nbsp;simple-produced&nbsp;sessions are easier to grade your sound setup, since you can more easily tell how real an instrument/voice sounds.</P>
<P>- Good speakers give you the ability to position the sounds within the soundstage, instead of offering one giant meltingpot of sounds.</P>
<P>- During evaluation, always listen to music the way it is recorded; if it's recorded in stereo, don't let it play in surround sound.</P>
<P>- Use cd's. MP3's or CD's made from MP3 songs filter out detail from he song, so it doesn't take as much space on disk as it originally does. While it is not very noticable, it might have the potential to conflict with you choosing the right speakers.</P>
<P>- Finally a strange one, and I have no clue if this is actually true : I think that better speakers deliver a better sound stage, so even when being far away/behind a wall, the sound still keeps a natural appearance. I have got no idea if this is bullocks or not, but&nbsp;I certainly noticed it.</P>
<P>Finally some music hints :<BR>- "fools gold"&nbsp;- the&nbsp;stone roses.<BR>- "Greatest hits" - the police<BR>- "Miles in blue" - miles davis</P>
<P>Good luck !!!</P>
<P>Ps: my choice : Canton Movie QX 150-set together with a teac reciever (de AG7D). </P><div style="text-align:right"><a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;pub=xa-4aec37702e3161d4"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pub=xa-4aec37702e3161d4"></script></div>
