---
layout: post
title: ! 'HOWTO : (Dutch) onderhandelen over je loon'
---

<DIV class=extra id=extra_25439734>De volgende vraag werd op een forum gesteld :</DIV>
<DIV class=extra>&nbsp;</DIV>
<DIV class=extra><EM><STRONG>...</STRONG></EM></DIV>
<DIV class=extra><EM><STRONG></STRONG></EM>&nbsp;</DIV>
<DIV class=extra><EM><STRONG>De nieuwe functie is echter een uurtje rijden en vereist dat ik goed bereikbaar ben. Ik kan een firmawagen krijgen, een GSM van de firma en zelfs een laptop van de firma. De firmawagen ben ik geneigd om te nemen. Dat komt ongetwijfeld veel goedkoper uit dan zelf kopen. De GSM waarschijnlijk ook, maar de laptop heb ik niet meteen een praktisch nut voor.<BR><BR>Nu is mijn vraag wat dit allemaal waard is? Hoeveel euro's (bruto/netto) vertegenwoordigt een firmawagen op een loon? En een GSM? En een laptop?<BR><BR>Ik verdien nu ongeveer 2400 euro bruto per maand. Ik wil er in m'n nieuwe functie natuurlijk wel iets op vooruitgaan, maar dan moet ik wel weten hoeveel een auto, gsm en laptop waard zijn in een loon. Kwestie van niet onder m'n huidige loon te gaan en ook weer niet te overdrijven.</STRONG></EM></DIV>
<DIV class=extra>&nbsp;</DIV>
<DIV class=extra><U>Mijn antwoord :</U></DIV>
<DIV class=extra>&nbsp;</DIV>
<DIV class=extra>Een tip : onderhandel eerst over je brutoloon, zonder enige 'voordelen in natura'. <BR>Als je weet hoeveel je werkgever bruto aan jou kan besteden, ga dan de onderverdeling gaan inkleden...<BR><BR>Het voordeel van een bedrijfswagen, is dat het leasebedrag van je bruto gaat, en niet van je netto. Gezien jouw huidige loon zou ik zeker opteren voor een bedrijfswagen, aangezien van je bruto waarschijnlijk bijna +/-40 % afgehouden wordt, en een lease-auto je dus 40% minder kost dan privé.<BR><BR>Houd er ook rekening mee dat een auto als voordeel in natura beschouwd wordt, en dat je dus op je prive-belastingen sowiezo zal moeten bijbetalen voor deze auto (ik meen me te herinneren 5000KM, maar dat is bij mij al enkele jaren geleden, en kan misschien wel verkeerd zijn).<BR><BR>GSM &amp; Portable van de zaak heb ikzelf eerlijkgezegd liever niet; dit is nl meestal een synoniem voor permanente beschikbaarheid/werken in je vrije tijd van thuis uit....<BR><BR>Andere alternatieven zijn groepsverzekering, maaltijdcheques, hospitalisatieverzekering, en als je een relatief hoge functie hebt kan je (onbelast) voor 250 € per maand representatiekosten vragen.<BR>Verder zijn er nog ... minder courante mogelijkheden, denk bv aan geschenkencheques, etentjes, incentives onder de vorm van reizen... Veel hangt af van de flexibiliteit van je (toekomstige) werkgever, en je vermogen om 'jezelf te verkopen'. Succes !!</DIV><div style="text-align:right"><a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;pub=xa-4aec37702e3161d4"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pub=xa-4aec37702e3161d4"></script></div>
