---
layout: post
title: Why choose ASP.NET MVC as a web development platform
---

<p>Microsoft has recently released their <a href="http://www.microsoft.com/downloads/details.aspx?FamilyID=53289097-73ce-43bf-b6a6-35e00103cb4b&amp;displaylang=en" target="_blank">final version of ASP.NET MVC</a>.</p>
<p>A few months ago I investigated some time in studying this new framework (while it was in beta 3).<br /> After studying it, Core decided to migrate all current webdevelopment to this new framework, and all future web-based projects will be written in this technology as well.</p>
<p>Since most people do not know what ASP.NET MVC is and why it should be used in favor of regular ASP.NET,I would like to clarify this choice a little bit.</p>
<p>For the technical people, I am posting a link to an in-depth introduction about ASP.NET MVC, which will let you decide for yourself :<br /> <a href="http://channel9.msdn.com/pdc2008/PC21/" target="_blank">An in-depth introduction to ASP.Net MVC bij Phil Haacked (PM for ASP.NET MVC)</a></p>
<p>For the less-technical people, I can only give you a few pointers, since it is a technical framework :<br /> ASP.Net MVC is a new <a href="http://haacked.com/archive/2009/04/01/aspnetmvc-open-source.aspx" target="_blank">community-driven open framework</a> by Microsoft that leverages ASP.NET to a very "<a href="http://en.wikipedia.org/wiki/Web_2.0" target="_blank">WEB 2.0</a>"-friendly,"<a href="http://rubyonrails.org/" target="_blank">ruby on rails</a>"-like toolkit.<br /> The biggest assets are :<br /> - <a href="http://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller">MVC</a> (Mode-View-Controller) paradigm : makes sure that your sourcecode is very-well structured, and usually almost the same for each ASP.NET MVC project. In other words, if a developper knows ASP.NET MVC, the project will look familiar to him/her...<br /> - Modularity : makes sure you can exchange components for other ones without many hassle. (I.e. to extend functionality/fix bugs/improve performance.)<br /> - The layout/business logic/back-end etc can be developed in parallel with each other without much inteference.<br /> <br /> While it is still possible to make a mess of your code, in ASP.Net MVC it is less likely to happen.<br /> Please note that <strong>this framework does not replace a development framework or the need for a decent software architecture</strong>; here at Core, for example, we still develop our business-layers in a separate project (using IOC/Castle windsor and IRepository&lt;T&gt;/Fluent-NHibernate/Linq to name a few buzzwords).</p>
<p>I do hope this clarifies the choice for ASP.NET MVC a little bit.</p><div style="text-align:right"><a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;pub=xa-4aec37702e3161d4"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pub=xa-4aec37702e3161d4"></script></div>
