---
layout: post
title: ! 'M-V-VM in Asp.Net MVC : removing dependencies between asp.Net views and
  controller actions'
---

<p>Since the early days I have always been a fan of the ASP.net MVC framework, although I had one really big issue with it : the coupling of the controller actions in the view pages. This part was a real annoyance, since all the flow and logic was included in the controller, and none of it in the views, _except_ the action flow; this was included in the views by using Html.ActionLink.</p>
<p>This has always been a nuisance for me, so last week, as I was working on a project, I decided to fix this issue...</p>
<p>IMHO the possible proceeding controller <strong>actions in the program flow should be defined in the controller</strong> action, <strong>and not in the view</strong>. So how could we do this, while still making it maintainable and easy to follow ?</p>
<p>After considering a few alternative routes, and thinking about it event more, it suddenly hit me; why not represent the possible routes as data.</p>
<p>A few development cycles later I had the following code in the controller:</p>
<p><div class="code">
<br /><span class="kwrd">public</span> ActionResult Index()<br />{<br />&nbsp;&nbsp;&nbsp;&nbsp; ViewData.Model = <span class="kwrd">new</span> VMIndex()<br />&nbsp;&nbsp;&nbsp;&nbsp; {<br />&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; AllTasks = rTask.Find.OrderBy(o =&gt; o.Name),<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; AL_AddTask = <span class="kwrd">this</span>.ActionLink(<span class="str">"Add new task"</span>,c=&gt;c.AddNewTask(<span class="kwrd">null</span>,<span class="kwrd">null</span>))<br />&nbsp;&nbsp;&nbsp;&nbsp; };<br />&nbsp;&nbsp;&nbsp;&nbsp; <span class="kwrd">return</span> View();<br />}<br /></div></p>
<p>And this code in the view :</p>
<p><div class="code">
<br />&lt;h1&gt;Task list&lt;/h1&gt;<br />&lt;%= Html.Grid(Model.AllTasks)<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .Columns(c=&gt; {<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; c.For(t =&gt; t.Name);<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; c.For(t =&gt; t.Description);<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; c.For(t =&gt; Html.ActionLink(t.AL_Status())).Named(<span class="str">"Status"</span>).DoNotEncode();<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; c.For(t =&gt; Html.ActionLink(t.AL_Edit())).Named(<span class="str">"Edit"</span>).DoNotEncode();<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; c.For(t =&gt; Html.ActionLink(t.AL_Delete())).Named(<span class="str">"Delete"</span>).DoNotEncode();<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }).Empty(<span class="str">"No tasks yet"</span>) <br />%&gt;<br />&lt;hr /&gt;<br />&lt;h3&gt;Add a <span class="kwrd">new</span> task&lt;/h3&gt;<br />&lt;% <span class="kwrd">using</span> (Html.BeginForm(Model.AL_AddTask)) { %&gt;<br />&nbsp;&nbsp;&nbsp; Name&lt;br /&gt;<br />&nbsp;&nbsp;&nbsp; &lt;%=Html.TextBox(<span class="str">"Name"</span>) %&gt;&lt;br /&gt;<br />&nbsp;&nbsp;&nbsp; Description&lt;br /&gt;<br />&nbsp;&nbsp;&nbsp; &lt;%=Html.TextArea(<span class="str">"Description"</span>) %&gt;&lt;br /&gt;<br />&nbsp;&nbsp;&nbsp; &lt;%=Html.SubmitButton(Model.AL_AddTask) %&gt;&lt;br /&gt;<br />&lt;% }%&gt; <br /></div></p>
<p>Which looks rather nice in my opinion. Since I do not know whether I am the first person who thinks about this or not, I decided to publish the sourcecode together with an example on <a href="http://github.com/ToJans/MVCExtensions" target="_blank">github</a>.</p>
<p>The technical implementation is actually quite simple; I implement the <a href="http://msdn.microsoft.com/en-us/magazine/dd419663.aspx" target="_blank">Model-View-Viewmodel</a> pattern, which is used in WPF, using a simple wrapper class for the action links (i.e. commands in MVVM). Once I made that link, the rest was childs play.</p>
<p>Next to this I also created some helper extensions, to make the code a little easier on the eyes.</p>
<p>I also think that by using this pattern we should be able to implement a winforms/WPF app using the same controller. Anybody who is willing to send me a git patch of a WPF application using this controller: please do !!!</p>
<p>PS: This also makes the actionlinks testable in an easy way; another responsibility that has been taken away from the view !!!</p><div style="text-align:right"><a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;pub=xa-4aec37702e3161d4"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pub=xa-4aec37702e3161d4"></script></div>
