---
layout: post
title: ! 'Project #Startup10: Working title - BIG'
---

<p>note: The source for this project is on <a href="https://github.com/ToJans/Big" target="_blank">Github</a>; the following text is a copy of the file <a href="https://github.com/ToJans/Big/blob/master/readme.md" target="_blank">Readme.md</a>.</p>
<h1 style="margin: 0px 0px 10px; padding: 0px; border: 0px; -webkit-font-smoothing: antialiased; cursor: text; position: relative; font-size: 28px; font-family: Helvetica, arial, freesans, clean, sans-serif;">
<p>Project #Startup10 - Startup #3 : Project Big</p>
</h1>
<p style="margin: 0px 0px 15px; padding: 0px; border: 0px; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">This is one of the projects of a bigger one:&nbsp;<a style="margin: 0px; padding: 0px; border: 0px; color: #4183c4; text-decoration: none;" href="http://www.corebvba.be/blog/post/Project-Startup10-Learning-to-build-your-own-business.aspx">Project #StartUp10: Creating 10 Startups in one year</a>.</p>
<p style="margin: 15px 0px; padding: 0px; border: 0px; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">The idea of project #3 was to create a platform to implement some really quick solutions for small problems. I would come to a customer, anayze the small issue in about 2-4 hours; implement it in the same timeframe, and by the end of the day the customer should have a working solution.</p>
<p style="margin: 15px 0px; padding: 0px; border: 0px; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">The solution implementation would have been lowcost, but there would be a small recurring fixed amount/month/user fee.</p>
<h2 style="margin: 20px 0px 10px; padding: 0px; border-width: 0px 0px 1px; border-bottom-style: solid; border-bottom-color: #cccccc; -webkit-font-smoothing: antialiased; cursor: text; position: relative; font-size: 24px; font-family: Helvetica, arial, freesans, clean, sans-serif;"><a class="anchor" style="margin: 0px 0px 0px -30px; padding: 0px 0px 0px 30px; border: 0px; color: #4183c4; text-decoration: none; display: block; cursor: pointer; position: absolute; top: 0px; left: 0px; bottom: 0px;" name="architecture" href="https://github.com/ToJans/Big/blob/master/readme.md#architecture"></a>Architecture</h2>
<p style="margin: 0px 0px 15px; padding: 0px; border: 0px; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">It is currently still completely running clientside, and is just a very simple concept</p>
<ul style="margin: 15px 0px; padding: 0px 0px 0px 30px; border: 0px; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">
<li style="margin: 0px; padding: 0px; border: 0px;">you have assets or code with a mime-type</li>
<li style="margin: 0px; padding: 0px; border: 0px;">interaction between code happens using events</li>
</ul>
<p style="margin: 15px 0px; padding: 0px; border: 0px; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">The idea was to distribute these events to other clients and the server using signalr or something similar</p>
<h2 style="margin: 20px 0px 10px; padding: 0px; border-width: 0px 0px 1px; border-bottom-style: solid; border-bottom-color: #cccccc; -webkit-font-smoothing: antialiased; cursor: text; position: relative; font-size: 24px; font-family: Helvetica, arial, freesans, clean, sans-serif;"><a class="anchor" style="margin: 0px 0px 0px -30px; padding: 0px 0px 0px 30px; border: 0px; color: #4183c4; text-decoration: none; display: block; cursor: pointer; position: absolute; top: 0px; left: 0px; bottom: 0px;" name="example" href="https://github.com/ToJans/Big/blob/master/readme.md#example"></a>Example</h2>
<p style="margin: 0px 0px 15px; padding: 0px; border: 0px; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">Here is a simple example to prove the concept</p>
<h3 style="margin: 20px 0px 10px; padding: 0px; border: 0px; font-size: 18px; -webkit-font-smoothing: antialiased; cursor: text; position: relative; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif;"><a class="anchor" style="margin: 0px 0px 0px -30px; padding: 0px 0px 0px 30px; border: 0px; color: #4183c4; text-decoration: none; display: block; cursor: pointer; position: absolute; top: 0px; left: 0px; bottom: 0px;" name="codedomainalerter---textx-coffeescript" href="https://github.com/ToJans/Big/blob/master/readme.md#codedomainalerter---textx-coffeescript"></a>code://Domain.Alerter - text/x-coffeescript</h3>
<div class="highlight" style="margin: 0px; padding: 0px; border: none; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">
<pre style="margin: 15px 0px; padding: 6px 10px; border: 1px solid #cccccc; font-size: 13px; font-family: Consolas, 'Liberation Mono', Courier, monospace; background-color: #f8f8f8; line-height: 19px; overflow: auto; border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px;"><span class="k" style="margin: 0px; padding: 0px; border: 0px; font-weight: bold;">class</span> <span class="nx" style="margin: 0px; padding: 0px; border: 0px;">Alerter</span>

  <span class="nv" style="margin: 0px; padding: 0px; border: 0px; color: #008080;">alertcount: </span><span class="mi" style="margin: 0px; padding: 0px; border: 0px; color: #009999;">0</span>

  <span class="nv" style="margin: 0px; padding: 0px; border: 0px; color: #008080;">alert: </span><span class="nf" style="margin: 0px; padding: 0px; border: 0px; color: #990000; font-weight: bold;">(message) -&gt;</span>
    <span class="k" style="margin: 0px; padding: 0px; border: 0px; font-weight: bold;">if</span> <span class="p" style="margin: 0px; padding: 0px; border: 0px;">(</span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">@alertcount</span> <span class="o" style="margin: 0px; padding: 0px; border: 0px; font-weight: bold;">&lt;</span> <span class="mi" style="margin: 0px; padding: 0px; border: 0px; color: #009999;">5</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">)</span>
      <span class="nx" style="margin: 0px; padding: 0px; border: 0px;">emit</span> <span class="s" style="margin: 0px; padding: 0px; border: 0px; color: #dd1144;">'alerted'</span>
        <span class="nv" style="margin: 0px; padding: 0px; border: 0px; color: #008080;">message: </span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">message</span>

  <span class="nx" style="margin: 0px; padding: 0px; border: 0px;">handle</span> <span class="s" style="margin: 0px; padding: 0px; border: 0px; color: #dd1144;">'alerted'</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">,</span> <span class="nf" style="margin: 0px; padding: 0px; border: 0px; color: #990000; font-weight: bold;">(e) -&gt;</span>
    <span class="nx" style="margin: 0px; padding: 0px; border: 0px;">@alertcount</span><span class="o" style="margin: 0px; padding: 0px; border: 0px; font-weight: bold;">+=</span><span class="mi" style="margin: 0px; padding: 0px; border: 0px; color: #009999;">1</span>
</pre>
</div>
<h3 style="margin: 20px 0px 10px; padding: 0px; border: 0px; font-size: 18px; -webkit-font-smoothing: antialiased; cursor: text; position: relative; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif;"><a class="anchor" style="margin: 0px 0px 0px -30px; padding: 0px 0px 0px 30px; border: 0px; color: #4183c4; text-decoration: none; display: block; cursor: pointer; position: absolute; top: 0px; left: 0px; bottom: 0px;" name="codedenormalizerinvoice---textx-coffeescript" href="https://github.com/ToJans/Big/blob/master/readme.md#codedenormalizerinvoice---textx-coffeescript"></a>code://Denormalizer.Invoice - text/x-coffeescript</h3>
<div class="highlight" style="margin: 0px; padding: 0px; border: none; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">
<pre style="margin: 15px 0px; padding: 6px 10px; border: 1px solid #cccccc; font-size: 13px; font-family: Consolas, 'Liberation Mono', Courier, monospace; background-color: #f8f8f8; line-height: 19px; overflow: auto; border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px;"><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">handle</span> <span class="s" style="margin: 0px; padding: 0px; border: 0px; color: #dd1144;">'alerted'</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">,</span> <span class="nf" style="margin: 0px; padding: 0px; border: 0px; color: #990000; font-weight: bold;">(e) -&gt;</span>
  <span class="nx" style="margin: 0px; padding: 0px; border: 0px;">loader</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">.</span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">modifyTable</span> <span class="s" style="margin: 0px; padding: 0px; border: 0px; color: #dd1144;">'table://invoice/123'</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">,</span> <span class="o" style="margin: 0px; padding: 0px; border: 0px; font-weight: bold;">-&gt;</span>
    <span class="nx" style="margin: 0px; padding: 0px; border: 0px;">@A5</span> <span class="o" style="margin: 0px; padding: 0px; border: 0px; font-weight: bold;">+=</span> <span class="mi" style="margin: 0px; padding: 0px; border: 0px; color: #009999;">1</span>
    <span class="vi" style="margin: 0px; padding: 0px; border: 0px; color: #008080;">@B5 = </span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">e</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">.</span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">message</span>
  <span class="nx" style="margin: 0px; padding: 0px; border: 0px;">alert</span> <span class="p" style="margin: 0px; padding: 0px; border: 0px;">(</span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">e</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">.</span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">message</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">)</span>
</pre>
</div>
<h3 style="margin: 20px 0px 10px; padding: 0px; border: 0px; font-size: 18px; -webkit-font-smoothing: antialiased; cursor: text; position: relative; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif;"><a class="anchor" style="margin: 0px 0px 0px -30px; padding: 0px 0px 0px 30px; border: 0px; color: #4183c4; text-decoration: none; display: block; cursor: pointer; position: absolute; top: 0px; left: 0px; bottom: 0px;" name="codeexample---textx-coffeescript" href="https://github.com/ToJans/Big/blob/master/readme.md#codeexample---textx-coffeescript"></a>code://Example - text/x-coffeescript</h3>
<div class="highlight" style="margin: 0px; padding: 0px; border: none; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">
<pre style="margin: 15px 0px; padding: 6px 10px; border: 1px solid #cccccc; font-size: 13px; font-family: Consolas, 'Liberation Mono', Courier, monospace; background-color: #f8f8f8; line-height: 19px; overflow: auto; border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px;"><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">code</span><span class="o" style="margin: 0px; padding: 0px; border: 0px; font-weight: bold;">://</span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">Domain</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">.</span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">Alerter</span>
<span class="nx" style="margin: 0px; padding: 0px; border: 0px;">code</span><span class="o" style="margin: 0px; padding: 0px; border: 0px; font-weight: bold;">://</span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">Denormalizer</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">.</span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">Invoice</span>

<span class="nv" style="margin: 0px; padding: 0px; border: 0px; color: #008080;">SUT = </span><span class="k" style="margin: 0px; padding: 0px; border: 0px; font-weight: bold;">new</span> <span class="nx" style="margin: 0px; padding: 0px; border: 0px;">Alerter</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">()</span>
<span class="k" style="margin: 0px; padding: 0px; border: 0px; font-weight: bold;">for</span> <span class="nx" style="margin: 0px; padding: 0px; border: 0px;">i</span> <span class="k" style="margin: 0px; padding: 0px; border: 0px; font-weight: bold;">in</span> <span class="p" style="margin: 0px; padding: 0px; border: 0px;">[</span><span class="mi" style="margin: 0px; padding: 0px; border: 0px; color: #009999;">1</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">..</span><span class="mi" style="margin: 0px; padding: 0px; border: 0px; color: #009999;">10</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">]</span>
  <span class="nx" style="margin: 0px; padding: 0px; border: 0px;">SUT</span><span class="p" style="margin: 0px; padding: 0px; border: 0px;">.</span><span class="nx" style="margin: 0px; padding: 0px; border: 0px;">alert</span> <span class="s" style="margin: 0px; padding: 0px; border: 0px; color: #dd1144;">"Woohoo #{i}"</span>

<span class="nx" style="margin: 0px; padding: 0px; border: 0px;">report</span> <span class="s" style="margin: 0px; padding: 0px; border: 0px; color: #dd1144;">"&lt;h1&gt;Done&lt;/h1&gt;"</span>
</pre>
</div>
<h3 style="margin: 20px 0px 10px; padding: 0px; border: 0px; font-size: 18px; -webkit-font-smoothing: antialiased; cursor: text; position: relative; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif;"><a class="anchor" style="margin: 0px 0px 0px -30px; padding: 0px 0px 0px 30px; border: 0px; color: #4183c4; text-decoration: none; display: block; cursor: pointer; position: absolute; top: 0px; left: 0px; bottom: 0px;" name="how-does-it-work-" href="https://github.com/ToJans/Big/blob/master/readme.md#how-does-it-work-"></a>How does it work ?</h3>
<p style="margin: 0px 0px 15px; padding: 0px; border: 0px; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">First you need to add the code resources mentioned on top as well as a "Data resource" named "invoice/123"</p>
<p style="margin: 15px 0px; padding: 0px; border: 0px; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">Then you press "Run" on the example, et voila, everything should work/compile, and you should see the updates in the excel-like grid in green, and a "report" saying "Done"</p>
<h2 style="margin: 20px 0px 10px; padding: 0px; border-width: 0px 0px 1px; border-bottom-style: solid; border-bottom-color: #cccccc; -webkit-font-smoothing: antialiased; cursor: text; position: relative; font-size: 24px; font-family: Helvetica, arial, freesans, clean, sans-serif;"><a class="anchor" style="margin: 0px 0px 0px -30px; padding: 0px 0px 0px 30px; border: 0px; color: #4183c4; text-decoration: none; display: block; cursor: pointer; position: absolute; top: 0px; left: 0px; bottom: 0px;" name="demo" href="https://github.com/ToJans/Big/blob/master/readme.md#demo"></a>Demo</h2>
<p style="margin: 0px 0px 15px; padding: 0px; border: 0px; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">As usual, you can find the demo over at Appharbor:&nbsp;<a style="margin: 0px; padding: 0px; border: 0px; color: #4183c4; text-decoration: none;" href="http://big.apphb.com/editor/">here</a>.</p>
<h2 style="margin: 20px 0px 10px; padding: 0px; border-width: 0px 0px 1px; border-bottom-style: solid; border-bottom-color: #cccccc; -webkit-font-smoothing: antialiased; cursor: text; position: relative; font-size: 24px; font-family: Helvetica, arial, freesans, clean, sans-serif;"><a class="anchor" style="margin: 0px 0px 0px -30px; padding: 0px 0px 0px 30px; border: 0px; color: #4183c4; text-decoration: none; display: block; cursor: pointer; position: absolute; top: 0px; left: 0px; bottom: 0px;" name="why-are-you-not-persueing-with-this-projectstartup-" href="https://github.com/ToJans/Big/blob/master/readme.md#why-are-you-not-persueing-with-this-projectstartup-"></a>Why are you not persueing with this project/Startup ?</h2>
<p style="margin: 0px 0px 15px; padding: 0px; border: 0px; color: #333333; font-family: Helvetica, arial, freesans, clean, sans-serif; font-size: 14px; line-height: 22px;">Every single person I mention this to does not "get it", so I consider this not the way to go... For now at least. Maybe I will continue with this later on, but for now, I consider this a failure.</p>
<h1 style="margin-top: 20px; margin-right: 0px; margin-bottom: 0px !important; margin-left: 0px; padding: 0px; border: 0px; -webkit-font-smoothing: antialiased; cursor: text; position: relative; font-size: 28px; font-family: Helvetica, arial, freesans, clean, sans-serif;"><a class="anchor" style="margin: 0px 0px 0px -30px; padding: 0px 0px 0px 30px; border: 0px; color: #4183c4; text-decoration: none; display: block; cursor: pointer; position: absolute; top: 0px; left: 0px; bottom: 0px;" name="ciao" href="https://github.com/ToJans/Big/blob/master/readme.md#ciao"></a>CIAO</h1>
<p>&nbsp;</p><div style="text-align:right"><a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;pub=xa-4aec37702e3161d4"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a><script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pub=xa-4aec37702e3161d4"></script></div>
